### ISSUE TITLE
Temperature sensors on flood sensors reporting unavailable after update from 3.2.4 to 3.2.5

### ISSUE THREAD

**Issue by cmegalodon** [sebr/bhyve-home-assistant#308]
**Describe the bug**
Temperature sensors on flood sensors reporting unavailable after update from 3.2.4 to 3.2.5

**Expected behaviour**
Temperature sensor should report a temperature

**BHyve devices**
14 devices, 13 of which are fs1-0001 (flood sensor) and one HT25G2-0001 (sprinkler)

**Device Diagnostics**
[home-assistant_bhyve_2025-06-26T15-09-37.558Z.log](https://github.com/user-attachments/files/20928747/home-assistant_bhyve_2025-06-26T15-09-37.558Z.log)

Not sure if the diagnostics file was uploaded, but this is an example of the error:

```
2025-06-26 10:43:59.330 ERROR (MainThread) [homeassistant.components.sensor] Error adding entity None for domain sensor with platform bhyve
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 657, in _async_add_entities
    await self._async_add_entity(
        entity, False, entity_registry, config_subentry_id
    )
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 892, in _async_add_entity
    unit_of_measurement=entity.unit_of_measurement,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/bhyve/sensor.py", line 371, in unit_of_measurement
    return self._unit
           ^^^^^^^^^^
AttributeError: 'BHyveTemperatureSensor' object has no attribute '_unit'


```

**Comment by cmegalodon** [comment]
Thanks Seb, it works perfectly! I really appreciate the work you've put in to this for the rest of the community.
